services:
  db:
    image: pgvector/pgvector:pg17 # Specify PostgreSQL version 17
    container_name: family-nexus-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=familynexus
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  api: # Your Flask application
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map port 5000 for local access (optional, remove for production)
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/familynexus
      - FLASK_ENV=development # Or "production" in production
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-east-1
      - S3_BUCKET=family-nexus-photos
      - S3_USE_SSL=false

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map container port 80 to host port 3000
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider # Add this line to fix the OpenSSL error
    depends_on:
      - api # Frontend depends on the API being available

volumes:
  db-data:
  minio_data:
