version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: family-nexus-db
    env_file: ../config/development.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    env_file: ../config/development.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  api:
    build:
      context: ../backend
      dockerfile: ../docker/dockerfiles/backend.Dockerfile
    ports:
      - "5000:5000"
    env_file: ../config/development.env
    volumes:
      - ../backend:/app
    depends_on:
      - db
      - minio

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/dockerfiles/frontend.Dockerfile
    ports:
      - "3000:3000"
    env_file: ../config/development.env
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  db-data:
  minio_data:
